export enum TrackerNetStations {
    BakerStreet = 'BST',
    CharingCross = 'CHX',
    EdwareRoadBakerloo = 'ERB',
    ElephantCastle = 'ELE',
    KensalGreen = 'KGN',
    Kenton = 'KNT',
    KilburnPark = 'KPK',
    LambethNorth = 'LAM',
    MaidaVale = 'MDV',
    Marylebone = 'MYB',
    NorthWembley = 'NWM',
    OxfordCircus = 'OXC',
    Paddington = 'PAD',
    PiccadillyCircus = 'PIC',
    QueensPark = 'QPK',
    RegentsPark = 'RPK',
    SouthKenton = 'SKT',
    StonebridgePark = 'SPK',
    WarwickAvenue = 'WAR',
    Waterloo = 'WLO',
    WembleyCentral = 'WEM',
    WillesdenJunction = 'WJN',
    Bank = 'BNK',
    Barkingside = 'BDE',
    BethnalGreen = 'BNG',
    BondStreet = 'BDS',
    BuckhurstHill = 'BHL',
    ChanceryLane = 'CYL',
    Chigwell = 'CHG',
    Debden = 'DEB',
    EalingBroadway = 'EBY',
    EastActon = 'EAC',
    Epping = 'EPP',
    Fairlop = 'FLP',
    GantsHill = 'GHL',
}

